---
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Install sysstat package
      apt:
        name: sysstat
        state: present

    - name: Run iostat command
      command: iostat -d -x /dev/xvda
      register: iostat_output

    - name: Display IOPS stats
      debug:
        msg: "{{ iostat_output.stdout_lines }}"